### PR TITLE
add CONFIG_BPF_SYSCALL=y

### PR DESCRIPTION
**Pull request by 3nprob**
Necessary for running docker with cgroupsv2

See https://github.com/opencontainers/runc/issues/2959

### CODE REVIEW

**Comment by Danct12** [comment]
Thanks for your contribution! Please bump pkgrel.

**Comment by 3nprob** [comment]
> Thanks for your contribution! Please bump pkgrel.

Thank you :)

Bumped

**Comment by Danct12** [comment]
Please squash your commits and follow our [contribution guidelines](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/master/CONTRIBUTING.md).

**Comment by 3nprob** [comment]
> Please squash your commits and follow our [contribution guidelines](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/master/CONTRIBUTING.md).

Done. Converting back to draft until compiled and tested

**Comment by Danct12** [comment]
This PR is now a part of 73bb477d50c5103aff0f1c2fc4620d6dd47aa85d. Thank you for your contribution!

**Pull request closed without merging**
