### PR TITLE
pkg: phosh: phosh: upgrade to 0.21.0

### PR DESCRIPTION
**Pull request by marek-lach**

### CODE REVIEW

**Comment by ArenM** [comment]
fyi you don't need to delete your fork, and fork this repo again to open a pull request, all you need to do is create a new branch. It looks like you closed a bunch of your other open PRs by deleting your old fork

**Comment by marek-lach** [comment]
> fyi you don't need to delete your fork, and fork this repo again to open a pull request, all you need to do is create a new branch. It looks like you closed a bunch of your other open PRs by deleting your old fork

I have decided to introduce less PRs at a slower pace, so they'll probably get merged faster.

**Comment by Danct12** [comment]
The problem is that you keep using GitHub built in web upload feature, that 
doesn't allow complex things like squashing or commit rename which make your 
job more difficult.

Try a better git client: https://git-scm.com/downloads

**Comment by Danct12** [comment]
I'll also be closing this too as we're already on 0.21.0 and applied the patch to fix animations crash.

**Pull request closed without merging**
