### PR TITLE
pkg: sxmo: danctnix-sxmo-settings,danctnix-sxmo-ui-meta,sxmo-utils-sway,sxmo-utils-dwm: new url

### PR DESCRIPTION
**Pull request by flyxyz123**

### CODE REVIEW

**Comment by ArenM** [comment]
Oof that's quite the commit message, probably better to have one commit for each package.

LGTM besides that, it looks like sr.ht treats urls as case sensitive.

**Comment by Danct12** [comment]
@ddevault Any explanation regarding this odd change?

**Comment by ddevault** [comment]
Yes, at one point we made the project URLs case-sensitive and had to clean up the duplicates.

**Comment by ArenM** [comment]
Bump, can we get this merged?

**Comment by Danct12** [comment]
Need pkgrel bump.

**Comment by Danct12** [comment]
@ArenM autocutsel has been removed from Arch Linux, it needs to be readded in order to get this PR merged.

**Comment by Danct12** [comment]
Superseded by #653

**Pull request closed without merging**
