### PR TITLE
pkg: phosh: feedbackd: Have alarms ring in quiet and silent profiles

### PR DESCRIPTION
**Pull request by kclisp**
Add a patch to have alarms ring in quiet and silent profiles.

Also upgrade feedbackd-device-themes to the current master, which just incorporates the current patches, so we can simplify the PKGBUILD.

Upstream has an issue for their gnome-clocks (https://source.puri.sm/Librem5/debs/gnome-clocks/-/issues/28), but they seem to not be working on it. I'll try to see what their current plans are on that.

### CODE REVIEW

**Comment by kclisp** [comment]
Fixed

**Comment by Danct12** [comment]
Please discuss this with upstream instead of carrying patches that will never be upstreamed without a good reason.

**Comment by kclisp** [comment]
I registered for an account last week, but it is "pending approval". Do
you know who I should contact regarding that?

**Comment by kclisp** [comment]
Closing this since the right way is to use a custom theme.

**Pull request closed without merging**
