### PR TITLE
pkg: pine64: linux-pine64: Add Crypto User Modules (for run iwd and bluez)

### PR DESCRIPTION
**Pull request by genofire**
fix (maybe) #67

### CODE REVIEW

**Comment by daniellandau** [comment]
It does take a bit more than that. Once you enable CAN, it needs answers to a bunch more questions, and asks for them interactively if not given in the config file.

**Comment by genofire** [comment]
like for `CONFIG_CAN_RAW` and `CONFIG_CAN_GS_USB` :)
yes i know, i do not know a good option how to contribute on a generated file

**Comment by daniellandau** [comment]
I checked that the options you enabled for iwd don't require anything extra. I've never used iwd, what's required to test it? I can also upload a build if you want to test it @genofire.

**Comment by genofire** [comment]
```bash
pacman -S iwd; systemctl enable --now iwd;
```
and check it with the `iwctl` console
nice commands are:
- iwctl station wlan0 scan
- iwctl station wlan0 get-networks
- iwctl station wlan0 connect X

replace `wpa_supplicated` on NetworkManager by creating the file:
`/etc/NetworkManager/conf.d/wifi_backend.conf`

with:
```ini
[device]
wifi.backend=iwd
```

**Comment by genofire** [comment]
so if i revert the CAN parameter you would merge?

**Comment by genofire** [comment]
On x64 archlinux - there are following modules .... like:
```
CONFIG_CRYPTO_USER_API_HASH=m
CONFIG_CRYPTO_USER_API_SKCIPHER=m
```

**Comment by daniellandau** [comment]
I'll try to test in the evening. I don't have any power to merge anything.

**Comment by daniellandau** [comment]
Seems to work. get-networks returns the list of networks around here. After adding that config file and rebooting I get the polkit popup to verify the network password (which is autofilled with the previously remembered password) and after hitting ok it connects. I'm not sure how to verify that it's really using iwd, but I guess it is.

**Comment by genofire** [comment]
I clean up this Pull Request (after you created a valid one for CAN #107).

So this should be it ;)

**Comment by genofire** [comment]
oh nice your #107 is already merged @daniellandau - so i rebased (and create a new hash) ... 

do you have a image somewhere?

**Comment by Danct12** [comment]
I've included this with 6355f437f1b8669663076228f4dab326bf282450

**Pull request closed without merging**
