### PR TITLE
pkg: sxmo: pn: rebuild

### PR DESCRIPTION
**Pull request by bgkillas**
icu change made it need a rebuild

### CODE REVIEW

**Comment by Danct12** [comment]
Can you please change the commit name to follow our [commit message guidelines](https://github.com/dreemurrs-embedded/Pine64-Arch/blob/master/CONTRIBUTING.md#commit-message-guidelines)?

**Comment by ArenM** [comment]
It looks like you only changed the title of the pr, not the commit message, it'd be great if you could update that so this can get merged.

**Comment by hamblingreen1** [comment]
please do, this would help the porting of framebufferphone's f_phone script which benefits from a pn rebuild.

**Comment by bgkillas** [comment]
best i can think of

**Comment by ArenM** [comment]
You need to squash the commits with `git rebaes -i HEAD~3`, and that'll let you edit the original commit. In the future if you need to edit the latest commit message you can use `git commit --amend`.

If you want a hand feel free to ping me on a more real-time platform, I'm `@Aren` on the pine64 discord server since I think I've seen you there.

**Comment by bgkillas** [comment]
my god i do not care enough someone else do it

**Pull request closed without merging**
