### PR TITLE
pkg: sxmo: sxmo-utils: update to 1.11

### PR DESCRIPTION
**Pull request by ArenM**
To do:
 - [x] update superd to 0.7, sxmo expects this version
 - [x] add pipewire-pulse to sxmo images in `arch-pine64-build`
 - [ ] some good thorough testing

### CODE REVIEW

**Comment by ArenM** [comment]
@Danct12 I think this is ready to be pushed to testing if you're ready

**Comment by Danct12** [comment]
Where's `0001-sxmo_hook_statusbar.sh-remove-to-fix-pango-markup.patch`?

**Comment by ArenM** [comment]
Fixed, I guess I need to write a lint to check my package sources

**Comment by Danct12** [comment]
LGTM

**Pull request merged**
